### ISSUE TITLE
create initial spring project

### ISSUE THREAD

**Issue by PaulRps** [PaulRps/library-api#1]
create the spring project on site https://start.spring.io/ by setting:

project: Maven
language: Java
group:  br.com
artifact: library-api
name: library api
description: An API to manage a library
packaging: Jar
Java: 17

It should be added the following dependencies:

Spring Data MongoDB (NoSql)
Spring Web
Spring Boot DevTools

**Comment by Pedr04rthur** [comment]
Concluído

**Comment by PaulRps** [comment]
you need to create a branch from that issue with dev as source branch
