### ISSUE TITLE
create API definition to Author resource

### ISSUE THREAD

**Issue by PaulRps** [PaulRps/library-api#2]
create the following endpoints to Author resource (/authors):

- GET /authors - returns all authors as a list and status 200
- GET /authors/{:id} - returns one author by ID and status 200
- POST /authors - create an Author passing the Author object on body and returns the generated ID and status 201
- PUT /authors - update an existing Author by passing on body the Author object with its ID and returns status 204
- DELETE /authors/{id} - delete an existing Author by ID and returns 204

When finish, attach the API definition on this issue. Use this site to create the API definition: https://editor-next.swagger.io/

**Comment by Pedr04rthur** [comment]
[authors.json](https://github.com/PaulRps/library-api/files/15302252/authors.json)

Só consegui enviar em formato de JSON
