### ISSUE TITLE
create API definition to Category resource

### ISSUE THREAD

**Issue by PaulRps** [PaulRps/library-api#3]
create the following endpoints to Category resource (/categories):

- GET /categories - returns all Categories as a list and status 200
- GET /categories/{:id} - returns one Category by ID and status 200
- POST /categories - create an Category passing the Category object on body and returns the generated ID and status 201
- PUT /categories - update an existing Category by passing on body the Author object with its ID and returns status 204
- DELETE /categories/{id} - delete an existing Category by ID and returns 204

When finish, attach the API definition on this issue. Use this site to create the API definition: https://editor-next.swagger.io/

**Comment by PaulRps** [comment]
[library_api.yaml.zip](https://github.com/PaulRps/library-api/files/15065048/library_api.yaml.zip)

created api definition of category resource, when the next resource is going to be created, import this file on the site Swagger Editor and continues the job.

**Comment by Pedr04rthur** [comment]
[swagger.json](https://github.com/PaulRps/library-api/files/15302125/swagger.json)


só consegui enviar convertendo para json, o github não suporta o tipo yaml

**Comment by Pedr04rthur** [comment]
[categories.json](https://github.com/PaulRps/library-api/files/15302150/categories.json)
