### ISSUE TITLE
create the API defition to Book resource (/books):

### ISSUE THREAD

**Issue by PaulRps** [PaulRps/library-api#4]
- GET /books - returns all Books as a list and status 200
- GET /books/{:id} - returns one Book by ID and status 200
- POST /books - create a Book passing the Book object on body and returns the generated ID and status 201
- PUT /books - update an existing Book by passing on body the Book object with its ID and returns status 204
- DELETE /books/{id} - delete an existing Book by ID and returns 204

When finish, attach the API definition on this issue. Use this site to create the API definition: https://editor-next.swagger.io/

**Comment by Pedr04rthur** [comment]
Só consegui enviar em formato JSON
[books.json](https://github.com/PaulRps/library-api/files/15302198/books.json)
